# Generated by Django 4.2.9 on 2024-02-07 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("no_key", "Нет ключа"),
                            ("steal", "Украсть"),
                            ("change", "Изменить"),
                            ("trade", "Обмен"),
                            ("info", "Информация"),
                            ("reveal", "Раскрыть"),
                            ("heal", "Вылечить"),
                            ("delete", "Удалить"),
                            ("increase", "Увеличить"),
                            ("decrease", "Уменьшить"),
                        ],
                        default="no_key",
                        max_length=32,
                        verbose_name="Ключ действия",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("no_target", "Нет цели"),
                            ("self", "Себя"),
                            ("any", "Любого"),
                            ("all", "Все"),
                        ],
                        default="no_target",
                        max_length=32,
                        verbose_name="Цель действия",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("no_value", "Нет переменной"),
                            ("epidemia", "Эпидемия"),
                            ("bunker_type", "Тип бункера"),
                            ("bunker_room", "Комната бункера"),
                            ("bunker_suply", "Припасы в бункере"),
                            ("profession", "Профессия"),
                            ("age", "Возраст"),
                            ("gender", "Пол"),
                            ("orientation", "Ориентация"),
                            ("bio", "Био. Характеристики"),
                            ("health", "Здоровье"),
                            ("phobia", "Фобия"),
                            ("personality", "Характер"),
                            ("hobby", "Хобби"),
                            ("add_info", "Доп. Информация"),
                            ("item", "Багаж"),
                            ("bunker_place", "Мест в бункере"),
                        ],
                        default="no_value",
                        max_length=32,
                        verbose_name="Переменная действия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта Действия",
                "verbose_name_plural": "Карты Действия",
            },
        ),
        migrations.CreateModel(
            name="ActionCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.actioncart",
                        verbose_name="Карточка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка действий персонажа",
                "verbose_name_plural": "Карточки действий персонажа",
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(verbose_name="Возраст")),
                (
                    "action_carts",
                    models.ManyToManyField(
                        through="game.ActionCharacter", to="game.actioncart"
                    ),
                ),
            ],
            options={
                "verbose_name": "Персонаж",
                "verbose_name_plural": "Персонажи",
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "epidemia_time",
                    models.IntegerField(verbose_name="Лет до выхода на поверхность"),
                ),
                (
                    "bunker_place_amount",
                    models.IntegerField(verbose_name="Количество мест в бункере"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата начала игры"
                    ),
                ),
                (
                    "closed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания игры"
                    ),
                ),
            ],
            options={
                "verbose_name": "Игра",
                "verbose_name_plural": "Игры",
            },
        ),
        migrations.CreateModel(
            name="InformationCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("epidemia", "Эпидемия"),
                            ("bunker_type", "Тип бункера"),
                            ("bunker_room", "Комната бункера"),
                            ("profession", "Профессия"),
                            ("gender", "Пол"),
                            ("orientation", "Ориентация"),
                            ("health", "Здоровье"),
                            ("phobia", "Фобия"),
                            ("personality", "Характер"),
                            ("hobby", "Хобби"),
                            ("add_info", "Доп. Информация"),
                            ("item", "Багаж"),
                        ],
                        max_length=32,
                        verbose_name="Тип карты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта Информации",
                "verbose_name_plural": "Карты Информации",
            },
        ),
        migrations.CreateModel(
            name="UniqueCartGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.informationcart",
                        verbose_name="Карточка",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.game",
                        verbose_name="Игра",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уникальная карта в игре",
                "verbose_name_plural": "Уникальные карты в игре",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.IntegerField(unique=True, verbose_name="Номер комнаты"),
                ),
                (
                    "started",
                    models.BooleanField(default=False, verbose_name="Игра начата"),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_admin",
                        to="bot.user",
                        verbose_name="Администратор комнаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комната",
                "verbose_name_plural": "Комнаты",
            },
        ),
        migrations.CreateModel(
            name="InformationGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.informationcart",
                        verbose_name="Карточка",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.game",
                        verbose_name="Игра",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка информации игры",
                "verbose_name_plural": "Карточки информации игры",
            },
        ),
        migrations.CreateModel(
            name="InformationCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.informationcart",
                        verbose_name="Карточка",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.character",
                        verbose_name="Персонаж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка информации персонажа",
                "verbose_name_plural": "Карточки информации персонажа",
            },
        ),
        migrations.AddField(
            model_name="game",
            name="information_carts",
            field=models.ManyToManyField(
                related_name="information_carts",
                through="game.InformationGame",
                to="game.informationcart",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="unique_carts",
            field=models.ManyToManyField(
                related_name="unique_carts",
                through="game.UniqueCartGame",
                to="game.informationcart",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="game.game",
                verbose_name="Игра",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="information_carts",
            field=models.ManyToManyField(
                through="game.InformationCharacter", to="game.informationcart"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bot.user",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="actioncharacter",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="game.character",
                verbose_name="Персонаж",
            ),
        ),
    ]
