# Generated by Django 4.2.9 on 2024-02-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActionCarts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("no_key", "Нет ключа"),
                            ("steal", "Украсть"),
                            ("change", "Изменить"),
                            ("trade", "Обмен"),
                            ("info", "Информация"),
                            ("reveal", "Раскрыть"),
                            ("heal", "Вылечить"),
                            ("delete", "Удалить"),
                            ("increase", "Увеличить"),
                            ("decrease", "Уменьшить"),
                        ],
                        default="no_key",
                        max_length=32,
                        verbose_name="Ключ действия",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("no_target", "Нет цели"),
                            ("self", "Себя"),
                            ("any", "Любого"),
                            ("all", "Все"),
                        ],
                        default="no_target",
                        max_length=32,
                        verbose_name="Цель действия",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("no_value", "Нет переменной"),
                            ("epidemia", "Эпидемия"),
                            ("bunker_type", "Тип бункера"),
                            ("bunker_room", "Комната бункера"),
                            ("bunker_suply", "Припасы в бункере"),
                            ("profession", "Профессия"),
                            ("age", "Возраст"),
                            ("gender", "Пол"),
                            ("orientation", "Ориентация"),
                            ("bio", "Био. Характеристики"),
                            ("health", "Здоровье"),
                            ("phobia", "Фобия"),
                            ("personality", "Характер"),
                            ("hobby.csv", "Хобби"),
                            ("add_info", "Доп. Информация"),
                            ("item", "Багаж"),
                            ("bunker_place", "Мест в бункере"),
                        ],
                        default="no_value",
                        max_length=32,
                        verbose_name="Переменная действия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта Действия",
                "verbose_name_plural": "Карты Действия",
            },
        ),
        migrations.CreateModel(
            name="InformationCarts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("no_target", "Нет цели"),
                            ("self", "Себя"),
                            ("any", "Любого"),
                            ("profession", "Профессия"),
                            ("gender", "Пол"),
                            ("orientation", "Ориентация"),
                            ("health", "Здоровье"),
                            ("phobia", "Фобия"),
                            ("personality", "Характер"),
                            ("hobby.csv", "Хобби"),
                            ("add_info", "Доп. Информация"),
                            ("item", "Багаж"),
                        ],
                        max_length=32,
                        verbose_name="Тип карты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта Информации",
                "verbose_name_plural": "Карты Информации",
            },
        ),
    ]
