# Generated by Django 4.2.9 on 2024-02-08 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_initial"),
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="closed",
            field=models.BooleanField(default=False, verbose_name="Сыграна"),
        ),
        migrations.CreateModel(
            name="UserGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.game",
                        verbose_name="Игра",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь в игре",
                "verbose_name_plural": "Пользователи в игре",
            },
        ),
        migrations.AddField(
            model_name="game",
            name="users",
            field=models.ManyToManyField(
                related_name="users", through="game.UserGame", to="bot.user"
            ),
        ),
    ]
