# Generated by Django 4.2.9 on 2024-02-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InformationCarts",
            new_name="InformationCart",
        ),
    ]
