# Generated by Django 4.2.9 on 2024-02-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_game_closed_usergame_game_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="actioncart",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активная карта"),
        ),
        migrations.AddField(
            model_name="actioncharacter",
            name="is_used",
            field=models.BooleanField(default=False, verbose_name="Ипользована"),
        ),
        migrations.AlterField(
            model_name="actioncart",
            name="key",
            field=models.CharField(
                choices=[
                    ("no_key", "Нет ключа"),
                    ("steal", "Украсть"),
                    ("change", "Изменить"),
                    ("generate", "Сгенерировать"),
                    ("trade", "Обмен"),
                    ("info", "Информация"),
                    ("reveal", "Раскрыть"),
                    ("heal", "Вылечить"),
                    ("delete", "Удалить"),
                    ("increase", "Увеличить"),
                    ("decrease", "Уменьшить"),
                ],
                default="no_key",
                max_length=32,
                verbose_name="Ключ действия",
            ),
        ),
    ]
