# Generated by Django 4.2.9 on 2024-02-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_rename_informationcarts_informationcart"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ActionCarts",
            new_name="ActionCart",
        ),
    ]
