# Generated by Django 4.2.10 on 2024-02-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_actioncart_is_active_actioncharacter_is_used_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actioncart",
            name="key",
            field=models.CharField(
                choices=[
                    ("no_key", "Нет ключа"),
                    ("steal", "Украсть"),
                    ("change", "Изменить"),
                    ("generate_int", "Сгенерировать числовую информацию"),
                    ("generate_cart", "Сгенерировать карту"),
                    ("generate_bunker_cart", "Сгенерировать карту бункера"),
                    ("trade", "Обмен"),
                    ("info", "Информация"),
                    ("reveal", "Раскрыть"),
                    ("heal", "Вылечить"),
                    ("delete", "Удалить"),
                    ("increase", "Увеличить"),
                    ("decrease", "Уменьшить"),
                ],
                default="no_key",
                max_length=32,
                verbose_name="Ключ действия",
            ),
        ),
        migrations.AlterField(
            model_name="actioncart",
            name="value",
            field=models.CharField(
                choices=[
                    ("no_value", "Нет переменной"),
                    ("epidemia", "Эпидемия"),
                    ("bunker_type", "Тип бункера"),
                    ("bunker_room", "Комната бункера"),
                    ("bunker_supply", "Припасы в бункере"),
                    ("profession", "Профессия"),
                    ("age", "Возраст"),
                    ("gender", "Пол"),
                    ("orientation", "Ориентация"),
                    ("bio", "Био. Характеристики"),
                    ("health", "Здоровье"),
                    ("phobia", "Фобия"),
                    ("personality", "Характер"),
                    ("hobby", "Хобби"),
                    ("add_info", "Доп. Информация"),
                    ("item", "Багаж"),
                    ("bunker_place", "Мест в бункере"),
                ],
                default="no_value",
                max_length=32,
                verbose_name="Переменная действия",
            ),
        ),
    ]
