START_COMMAND = "start"
NEW_GAME_ROOM_COMMAND = "new"
ENTER_GAME_ROOM_COMMAND = "enter"
MY_GAME_ROOM_COMMAND = "my"
LEAVE_GAME_ROOM_COMMAND = "leave"
RULES_COMMAND = "rules"
HELP_COMMAND = "help"

START_DESCRIPTION = "Запустить бота"
NEW_GAME_ROOM_DESCRIPTION = "Создать игровую комнату"
ENTER_GAME_ROOM_DESCRIPTION = "Войти в игровую комнату"
MY_GAME_ROOM_DESCRIPTION = "Информация о моей игровой комнате"
LEAVE_GAME_ROOM_DESCRIPTION = "Выйти из игровой комнаты"
HELP_DESCRIPTION = "Получить помощь"
RULES_DESCRIPTION = "Правила игры"
