# Generated by Django 4.2.6 on 2023-12-26 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_game_character_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="game",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="bot.game",
                verbose_name="Игра",
            ),
            preserve_default=False,
        ),
    ]
