# Generated by Django 4.2.10 on 2024-02-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login_date",
        ),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Права администратора"
            ),
        ),
    ]
