# Generated by Django 4.2.6 on 2023-12-26 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_alter_character_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="bunker",
        ),
        migrations.AddField(
            model_name="game",
            name="bunker_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bunker_type",
                to="bot.cart",
                verbose_name="Тип бункера",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="room_one",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_one",
                to="bot.cart",
                verbose_name="Комната №1",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="room_three",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_three",
                to="bot.cart",
                verbose_name="Комната №3",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="room_two",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_two",
                to="bot.cart",
                verbose_name="Комната №2",
            ),
            preserve_default=False,
        ),
    ]
