# Generated by Django 4.2.6 on 2024-01-16 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0005_game_epidemia_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="room",
        ),
        migrations.RemoveField(
            model_name="game",
            name="room",
        ),
        migrations.AddField(
            model_name="game",
            name="bunker_place_amount",
            field=models.IntegerField(
                default=1, verbose_name="Количество мест в бункере"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bot.game",
                verbose_name="Игра",
            ),
        ),
    ]
