version: '3.4'
services:
  postgres-dev-db:
    image: postgres:15
    env_file:
      - ../../.env
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    container_name: postgres-container-bunker-dev
    volumes:
      - dev-bunker-postgres-data:/var/lib/postgresql/data
    command: -p 5433

volumes:
  dev-bunker-postgres-data:
