services:
  redis:
    image: redis:latest
    container_name: redis-coffee-bot
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always

  postgres-db:
    image: postgres:13.0-alpine
    container_name: postgres-container-randomcoffee
    env_file:
      - ../../.env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres-data:
