
services:
  postgres-db:
    image: postgres:15
    container_name: postgres-container-bunker
    env_file:
      - ../../.env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  static_value:
  media_value:
