version: '3.4'
services:
  postgres-dev-db:
    image: postgres:15
    env_file:
      - ../../.env
    expose:
      - "5434" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5434:5434"
    container_name: postgres-dev-bunker
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data
    command: -p 5434

volumes:
  dev-postgres-data:
