
services:
  postgres-db:
    image: postgres:15
    container_name: postgres-container-pacanbot
    env_file:
      - ../../env/prod.env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data


  bot:
      build: '../../src/'
      container_name: pacan-bot
      restart: always
      volumes:
        - static_value:/app/static/
        - media_value:/app/media/
        - ../../logs/bot/:/app/logs
      env_file:
        - ../../env/prod.env
      depends_on:
        - postgres-db



  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"

    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/

    depends_on:
        - bot

volumes:
  postgres-data:
  static_value:
  media_value:
