
services:
  redis:
    image: redis:latest
    container_name: redis-bunker-bot
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always

  postgres-db:
    image: postgres:15
    container_name: postgres-container-bunker
    env_file:
      - ../../.env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

  bot:
      image: oupsfed/bunker-telegram-bot
      container_name: bunker-bot
      restart: always
      command: >
        bash -c "python manage.py migrate &&
        python manage.py collectstatic --no-input &&
        python manage.py upload_carts &&
        uvicorn core.asgi:application --host 0.0.0.0 --port 8000"
      volumes:
        - static_value:/app/static/
        - media_value:/app/media/
      env_file:
        - ../../.env
      depends_on:
        - postgres-db
        - redis

  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ../nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

    depends_on:
        - bot

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  postgres-data:
  static_value:
  media_value:
  redis_data:
